-- Execute conectado ao banco desejado (ex.: muneradb).
-- O schema é explícito; o aplicativo sempre usa munera.*.
BEGIN;
CREATE SCHEMA IF NOT EXISTS munera;

CREATE TABLE IF NOT EXISTS munera.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  script_path TEXT NOT NULL UNIQUE,
  args JSONB NOT NULL DEFAULT '[]'::jsonb,
  env JSONB NOT NULL DEFAULT '{}'::jsonb,
  times TEXT[] NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  timeout_seconds INTEGER NOT NULL DEFAULT 3600 CHECK (timeout_seconds BETWEEN 1 AND 86400),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT times_not_empty CHECK (cardinality(times) > 0),
  CONSTRAINT args_array CHECK (jsonb_typeof(args) = 'array'),
  CONSTRAINT env_object CHECK (jsonb_typeof(env) = 'object')
);

-- Cada horário tem seu próximo disparo persistido separadamente.
CREATE TABLE IF NOT EXISTS munera.job_schedules (
  job_id BIGINT NOT NULL REFERENCES munera.jobs(id) ON DELETE CASCADE,
  time_hhmm CHAR(5) NOT NULL,
  next_run_at TIMESTAMPTZ NOT NULL,
  datetime TIMESTAMPTZ,
  period INTEGER,
  PRIMARY KEY(job_id, time_hhmm)
);
CREATE INDEX IF NOT EXISTS idx_job_schedules_due ON munera.job_schedules(next_run_at);

CREATE TABLE IF NOT EXISTS munera.executions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id BIGINT REFERENCES munera.jobs(id) ON DELETE SET NULL,
  job_name VARCHAR(150) NOT NULL,
  script_path TEXT NOT NULL,
  trigger VARCHAR(30) NOT NULL,
  status VARCHAR(20) NOT NULL CHECK (status IN ('running','success','failed','timeout','cancelled','interrupted','skipped')),
  pid INTEGER,
  exit_code INTEGER,
  signal VARCHAR(30),
  error_message TEXT,
  log_path TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_executions_job_started ON munera.executions(job_id, started_at DESC);

CREATE TABLE IF NOT EXISTS munera.audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action VARCHAR(50) NOT NULL,
  job_id BIGINT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMIT;

-- Crie usuário e banco separadamente, como administrador, se necessário:
-- CREATE ROLE munera_app LOGIN PASSWORD 'TROQUE_POR_UMA_SENHA_FORTE';
-- CREATE DATABASE muneradb OWNER munera_app;
-- GRANT USAGE ON SCHEMA munera TO munera_app;
-- GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA munera TO munera_app;
-- GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA munera TO munera_app;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA munera GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO munera_app;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA munera GRANT USAGE,SELECT ON SEQUENCES TO munera_app;
